package.json
src/components/dialogs/AddDebt.js
src/components/dialogs/dialog_styles.js
src/screens/Balances.js

Briefly, updated addDebt to be cleaner ad more intuitive, auto height for dialog contents.

Mattsmithies dev

---

package.json
src/components/dialogs/AddDebt.js
src/components/dialogs/dialog_styles.js

Added additional spacing and titles for sections

Cleaner look for screenshot suitable create debt dialog

---

index.android.js
packages/theme/action-button.ts
packages/ui/components/action-button/index.tsx
packages/ui/components/popup/index.tsx

Action button rendering on android

Fixed display for action button on android, doesn't require parent view

---

packages/ui/dialogs/my-account/index.tsx

I'll leave restyling to future commits more specifically devoted to style.

adding mnemonic to my account screen, fixes #73

---

packages/lndr/engine/index.ts
packages/lndr/user/index.ts
packages/ui/forms/recover-account/index.tsx
packages/ui/views/account/friends/add-friend/index.tsx

also: updating wording for setting password upon recovering an account

fixing friend search logic, fixes #68

---

ios/LNDR.xcodeproj/project.pbxproj

- updating dev team to be BM industries, not Roy Blankman
- updating bundle id to not conflict with the one I created on Roy Blankman dev account

updated app bundle id to io.lndr

---

package.json
packages/reducers/index.ts
packages/theme/numpad.ts
packages/ui/components/numpad/index.tsx
packages/ui/fields/money-input.tsx
packages/ui/forms/add-debt/index.tsx
yarn.lock

Why:
* We need a better add debt form that allows the user to input numbers
easier
* Install/Configure redux forms
* Add Numpad Component
* Add Money Input field using numpad component
* Add Add Debt Stub Form Using Numpad field
* Update package.json

Feature - Add Debt Numpad

---

packages/actions/index.ts

> **Note:** Hold off on merging until supporting infrastructure work is complete.

🎨 Update back-end service URL to HTTPS and to use hostname vs IP

---

packages/language/languages/en.ts
packages/reducers/app.ts
packages/theme/account.ts
packages/theme/popup.ts
packages/ui/components/friend-row/index.tsx
packages/ui/components/pending-transaction-row/index.tsx
packages/ui/components/recent-transaction-row/index.tsx
packages/ui/components/spinning-picker/index.tsx
packages/ui/dialogs/add-debt/index.tsx
packages/ui/dialogs/friend-detail/index.tsx
packages/ui/dialogs/pending-transaction-detail/index.tsx
packages/ui/dialogs/settle-up/index.tsx
packages/ui/views/account/activity/pending/index.tsx
packages/ui/views/account/activity/recent/index.tsx

This is still a bunch of cleanup to do to remove the const arrays for currency lookup, etc.
Also, this does not support summing balances in multiple currencies.

Supports multi currency transactions

---

packages/navigators/dashboard.tsx
packages/theme/account.ts
packages/theme/button.ts
packages/ui/components/dashboard-shell/index.tsx
packages/ui/dialogs/add-debt/index.tsx
packages/ui/dialogs/confirmation-screen/index.tsx
packages/ui/dialogs/friend-detail/index.tsx
packages/ui/dialogs/friend-request/index.tsx
packages/ui/dialogs/my-account/index.tsx
packages/ui/dialogs/pending-settlement-detail/index.tsx
packages/ui/dialogs/pending-transaction-detail/index.tsx
packages/ui/dialogs/settle-up/index.tsx
packages/ui/dialogs/settlement/index.tsx
packages/ui/dialogs/transfer-bcpt/index.tsx
packages/ui/dialogs/transfer-eth/index.tsx
packages/ui/views/app/index.tsx

This is a big commit of UI fixes, primarily fixing the overarching scrollview problem but also a series of other UI bugfixes including keyboard covering text inputs.

Fix tabs in scrollview

---

ios/LNDR/Info.plist

removed landscape mode as an orientation for iOS

---

packages/language/languages/ar.ts
packages/language/languages/cs.ts
packages/language/languages/da.ts
packages/language/languages/de.ts
packages/language/languages/el.ts
packages/language/languages/en.ts
packages/language/languages/es.ts
packages/language/languages/fi.ts
packages/language/languages/fr.ts
packages/language/languages/hi.ts
packages/language/languages/hu.ts
packages/language/languages/in.ts
packages/language/languages/it.ts
packages/language/languages/iw.ts
packages/language/languages/ja.ts
packages/language/languages/ko.ts
packages/language/languages/ms.ts
packages/language/languages/nb.ts
packages/language/languages/nl.ts
packages/language/languages/no.ts
packages/language/languages/pl.ts
packages/language/languages/pt.ts
packages/language/languages/ru.ts
packages/language/languages/sv.ts
packages/language/languages/th.ts
packages/language/languages/tr.ts
packages/language/languages/vi.ts
packages/language/languages/zh-CN.ts
packages/ui/dialogs/my-account/index.tsx

When you review this, note the changes to the English file. Also, we might want to improve the wording on the Alert message (I only used the title, not description).

added confirmation alert when disconnecting PayPal account

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml

Please take a look and hopefully this is helpful.

Attempts to remove bad android permissions

---

packages/ui/dialogs/add-debt/index.tsx
packages/ui/dialogs/confirmation-screen/index.tsx
packages/ui/dialogs/friend-detail/index.tsx
packages/ui/dialogs/friend-request/index.tsx
packages/ui/dialogs/my-account/index.tsx
packages/ui/dialogs/remove-account/index.tsx
packages/ui/dialogs/settle-up/index.tsx
packages/ui/dialogs/settlement/index.tsx
packages/ui/dialogs/transfer-bcpt/index.tsx
packages/ui/dialogs/transfer-eth/index.tsx
packages/ui/views/account/activity/index.tsx
packages/ui/views/account/friends/index.tsx
packages/ui/views/account/home/index.tsx
packages/ui/views/authenticate/confirm-account/index.tsx
packages/ui/views/authenticate/create-account/index.tsx
packages/ui/views/authenticate/login/index.tsx
packages/ui/views/authenticate/recover-account/index.tsx
packages/ui/views/privacy-policy/index.tsx
packages/ui/views/welcome/welcome-step-four/index.tsx
packages/ui/views/welcome/welcome-step-one/index.tsx
packages/ui/views/welcome/welcome-step-three/index.tsx
packages/ui/views/welcome/welcome-step-two/index.tsx

I tried to get all of the important screens.

added Firebase.setCurrentScreen() to the primary Lndr screens

---

packages/actions/index.ts
packages/language/languages/de.ts
packages/ui/views/account/home/index.tsx
packages/ui/views/app/index.tsx

1. Jira: https://blockmason.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=ENG&selectedIssue=ENG-149
2. Problem: When a new user loads the app and does not have any friends, they see the Home screen with no useful info on it.
3. Solution: Route the friend to the Friends screen if they don't have any friends on load. To do this we need a flag for the initial load that will be changed when the user is routed to the Friends screen.
4. No concerns
5. No blockers

Reroute user to Friends screen if they load app and don't have any friends

---

packages/actions/index.ts
packages/language/index.ts
packages/language/languages/de.ts
packages/language/languages/es.ts
packages/language/languages/fr.ts
packages/language/languages/hu.ts
packages/language/languages/in.ts
packages/language/languages/it.ts
packages/language/languages/ms.ts
packages/language/languages/nl.ts
packages/language/languages/pl.ts
packages/language/languages/pt.ts
packages/language/languages/ru.ts
packages/language/languages/sv.ts
packages/reducers/app.ts
packages/theme/account.ts
packages/ui/components/balance-row/index.tsx
packages/ui/components/balance-section/index.tsx
packages/ui/dialogs/friend-detail/index.tsx
packages/ui/dialogs/pending-settlement-detail/index.tsx
packages/ui/dialogs/pending-transaction-detail/index.tsx
packages/ui/dialogs/settlement/index.tsx

1. Jira: https://blockmason.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=ENG&selectedIssue=ENG-124
2. Problem: The settlement descriptions were not detailed and in a multi-currency settlement all of the descriptions were the same. We want users to see all of the memos from prior transactions
3. Solution: Search through all of the prior memos and list all memos by currency since the last settlement. We need to check for "Settle" words in all languages
4. No concerns
5. No blockers

Settlement transaction descriptions

---

packages/theme/slide.ts
packages/theme/slideshow.ts
packages/ui/components/slideshow/index.tsx
packages/ui/views/welcome/index.tsx
packages/ui/views/welcome/welcome-step-five/index.tsx
packages/ui/views/welcome/welcome-step-one/index.tsx
packages/ui/views/welcome/welcome-step-three/index.tsx
packages/ui/views/welcome/welcome-step-two/index.tsx

These are the four issues outlined in ENG-205 and the one issue in ENG-206

Fixed 5 walkthrough issues

---

packages/language/languages/pl.ts

This is to fix 2 Polish-language corrections submitted by a community member to the Lndr Bugs Telegram channel.

Fixed 2 Polish translations

---

android/app/build.gradle
ios/LNDR/Info.plist
packages/lndr/format/index.ts
packages/ui/dialogs/my-account/index.tsx
packages/ui/dialogs/transfer-erc20/index.tsx
packages/ui/dialogs/transfer-eth/index.tsx

Cherry-picked the fixes that went into 1.4.1.

1.4.1 fixes

---

packages/theme/button.ts
packages/ui/components/back-button/index.tsx
packages/ui/dialogs/add-debt/index.tsx
packages/ui/dialogs/confirmation-screen/index.tsx
packages/ui/dialogs/friend-detail/index.tsx
packages/ui/dialogs/friend-request/index.tsx
packages/ui/dialogs/my-account/index.tsx
packages/ui/dialogs/paypal-request-detail/index.tsx
packages/ui/dialogs/pending-settlement-detail/index.tsx
packages/ui/dialogs/pending-transaction-detail/index.tsx
packages/ui/dialogs/settlement/index.tsx
packages/ui/dialogs/transfer-erc20/index.tsx
packages/ui/dialogs/transfer-eth/index.tsx
packages/ui/forms/verify-identity/index.tsx

There might be a better way to do this...

updated Back button padding and layout to fix Lndr-21

---

packages/language/languages/en.ts
packages/theme/button.ts
packages/theme/form.ts
packages/ui/components/button/index.tsx
packages/ui/dialogs/my-account/index.tsx

The first commit of a tighter layout for crypto balances. This needs localization (I added the word 'TRANSFER').

table style (horizonal) layout of crypto balances in my account

---

README.md

Very minor README updates here, mainly clarification and how to build Android for production

Updates to the README for v2.0 build

---

packages/actions/index.ts
packages/credit-protocol/index.ts

Removes the need for the server to attempt to send notifications for every language.

🔧 Add `language` to register/unregister push notifications

---

packages/lndr/erc-20/index.ts

Add the capability of transferring TrueUSD to/from LNDR wallets.

✨ Add support for TrueUSD ERC20 token transfers
