blockmason/lndr-mobile

- packages/language/en/index.ts
- packages/lndr/engine/index.ts
- before it was possible to create an account without setting a nick; this is
impossible now.
> adding length requirement for nicknames, fixes #69

- packages/theme/general.ts
- packages/ui/views/account/home/index.tsx
- packages/ui/views/authenticate/index.tsx
`light` theme was showing near the bottom of the auth view on Android. Matt noted this bug a few days ago.
> fixing auth view background on android

- packages/ui/components/balance-row/index.tsx
- packages/ui/views/account/home/index.tsx
- `titledFactAmountBad` & `factAmountBad` referred to non-existent styles, resulted in bad display of neg. balances
- changed these names to point to appropriate styles, s/Bad/Danger/g
note: The ui style code needs to be seriously cleaned up. Lots of bad var names like `goodDark`...
> Fix balances color

- package.json
- packages/lndr/engine/index.ts
- packages/ui/forms/recover-account/index.tsx
- decoupled mnemonic & password in seeding generation of HD private key
- incorporated salts in password
+ salt stored as part of hashed password, no separate salt storage is necessary
- trimming mnemonic input to handle leading and trailing whitespace
NOTE: if this version of the app is used, previously-stored mnemonics will not generate the same accounts. It will be necessary to make new accounts
> Feature unique salt

- packages/lndr/engine/index.ts
- packages/lndr/user/index.ts
Why:
* We need to move magic numbers to be reference at a single location for
readablity and management
* Create a new export in user for password length size
* Use pre existing nickname length variable to validate nickname length
> chore - remove nickname and password magic numbers

- packages/ui/views/account/friends/remove-friend/index.tsx
Why:
* We do not want to remove any friends with balances
* Add conditional to only render remove friend button when balance is 0
PLEASE NOTE - I could not test this since I don't have a dollar amount to test this. I hacked the render to show this, but we need to test this with actual data, before merging.
> Feature - Hide remove friend button that have balances

- packages/lndr/engine/index.ts
- packages/ui/views/app/index.tsx
- packages/ui/views/authenticate/create-account/index.tsx
- packages/ui/views/authenticate/index.tsx
- packages/ui/views/authenticate/recover-account/index.tsx
Why:
* We want to show Activity Indicator when the user is recovering their
login or creating a new account
* Add a new isAuthLoading key to the engine state
* Create a setter for that key in engine
* Pass isAuthLoading down to the authenticate view
* Wrap the createAccount/recoverAccount calls using the new flag
> Feature - Authentication Loading

- packages/ui/dialogs/pending-transaction-detail/index.tsx
Why:
* We need the ability to cancel any pending transaction if the user
created it on accident/incorrectly
* Adding the reject/cancel option to the popup modal when opening the
activity
> Feature - Cancel pending transactions that the user owns

- packages/ui/views/authenticate/login/index.tsx
Why:
* The user should get a Activity indicator when waiting to login after
they click the button
* Wrap isAuthLoading flag toggles around the login action
> Feature - Add Loading Screen for login action

- packages/language/en/index.ts
- packages/ui/dialogs/my-account/index.tsx
- packages/ui/views/authenticate/confirm-account/index.tsx
Why:
* We need to be able to copy the mnemonic text so that the user can
easily paste the words in a password manager
* Add Copy button for my account view
* Add Copy button for confirm account view
* Add lanuage const for copy text
> Feature - Add Copy for mnemonic

- packages/credit-protocol/index.ts
- packages/language/en/index.ts
- packages/lndr/engine/index.ts
- packages/ui/forms/create-account/index.tsx
- packages/ui/forms/login-account/index.tsx
- packages/ui/views/authenticate/create-account/index.tsx
- packages/ui/views/authenticate/login/index.tsx
Why:
* We want to check to see if there is a duplicate nick being created
when the user signs up
* Add taken_nick endpoint
* Apply endpoint to engine
* Update create account form view to house a state for invalid
duplication
* Pass a error text when there is a duplication state detected to the
form
* Update Text in lanuage for duplication error
> Feature - Login Duplication Check

- .env.example
- .gitignore
- README.md
- config/AirshipConfig.plist.example
- config/airshipconfig.properties.example
- config/settings.json
- package-lock.json
- package.json
- scripts/env.js
- yarn.lock
Why:
* We need a way to populate environmental data without saving them onto
the repo
* Add a settings json file to house file paths
* Add env example file for node to export vars
* Move example files into config directory
* Create a script to take in example file as templates and inject to the
proper dest
* Update README
> Chore - Add Env Setup Scripts

- packages/actions/index.ts
Why:
* We need to be able to search user with/without the @ symbol in front
* Update searchUsers function to trim off @ when inputted
> BugFix - Unable to search users using the @ symbol

- packages/ui/forms/create-account/index.tsx
- packages/ui/views/authenticate/create-account/index.tsx
On the create account screen, if a user entered an existing nickname or bad email address, the error messages would never disappear. This change causes those error messages to disappear as soon as the user makes a change to the text input.
> create account: clear nickname and email address error messages when user changes the text input

- packages/navigators/dashboard.tsx
- packages/theme/account.ts
- packages/theme/friend.ts
- packages/theme/tabs.ts
- packages/ui/components/dashboard-shell/index.tsx
- packages/ui/components/images/text-logo/index.tsx
- packages/ui/components/spinning-picker/index.tsx
- packages/ui/components/tabs/index.tsx
- packages/ui/dialogs/add-debt/index.tsx
- packages/ui/views/account/home/index.tsx
A series of commits to handle narrow screen layouts like iPhone SE, including:
LNDR-22: currency selector cut-off
LNDR-21: tab bar cut-off
Also includes:
LNDR-25: See All Activity too far down
LNDR-26: rounding avatar or Settle Up
> Fix narrow layout (e.g. iPhone SE)

- ios/LNDR.xcodeproj/project.pbxproj
- ios/LNDR/AppDelegate.m
- package.json
- packages/ui/views/app/index.tsx
Adds 'react-native-splash-screen' package and integrates it into the Xcode project
Note: this is only hooked up for iOS so far. Once it has been verified and is in the repo I can hook up Android.
> Fix for iOS white flash after native launchscreen

- packages/ui/dialogs/add-debt/index.tsx
- packages/ui/dialogs/my-account/index.tsx
- packages/ui/dialogs/settlement/index.tsx
- packages/ui/dialogs/transfer-bcpt/index.tsx
- packages/ui/forms/create-account/index.tsx
- packages/ui/forms/recover-account/index.tsx
I noticed that the KeyboardOverlayView was broken on Android. Looking into it, we need more platform-specific hard-coded values to make it work.
> add necessary vertical offset for Android to keyboard overlay

- packages/actions/index.ts
- packages/ui/dialogs/my-account/index.tsx
- packages/ui/forms/create-account/index.tsx
- packages/ui/forms/recover-account/index.tsx
- packages/ui/views/authenticate/index.tsx
1. Problem: PIN validation was not set up correctly on the MyAccount page. The user could previously set a new PIN after entering an incorrect PIN.  https://blockmason.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=ENG-51
2. Solution: Add an 'await' to the function that validates the PIN to wait for the boolean result, then display a message on PIN failure
3. No concerns
4. No blockers
> Fixed PIN validation for changing PIN

- packages/lndr/profile-pic/index.ts
- packages/navigators/index.tsx
- packages/theme/account.ts
- packages/ui/components/balance-section/index.tsx
- packages/ui/components/friend-row/index.tsx
- packages/ui/dialogs/friend-detail/index.tsx
1. Problem: Users cannot remove friends with whom they have transactions. https://blockmason.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=ENG-105
2. Solution: Show the user the 'Remove Friend' button on the FriendDetail screen when the users have transactions, and then show a short confirmation screen. The main added complexity is a removal confirmation screen and a separate Android BackHandler for that screen since it relies on setState rather than navigation
3. No trade-offs or concerns
4. No blockers
> Allow user to remove friend even if they have transactions

- packages/actions/index.ts
- packages/credit-protocol/index.ts
- packages/ui/dialogs/my-account/index.tsx
1. Problem: After updating the user's nickname (and email) and then navigating away from the MyAccount screen and back, the nickname would not be updated (although it was on the server). https://blockmason.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=ENG&modal=detail&selectedIssue=ENG-97
2. Solution: Modify the credit-protocol file to clear the in-memory cache of http calls. Update the updateNickname and updateEmail functions to modify the userStorage and the user object in the store.
3. No concerns
4. No blockers
> Fixed issue with nickname not updating after change

- packages/theme/form.ts
- packages/ui/components/add-friend-row/index.tsx
- packages/ui/components/friend-row/index.tsx
- packages/ui/views/account/friends/search-friend/index.tsx
- packages/ui/views/account/home/index.tsx
1. Problem: friend requests were not showing up due to a recent change. Avatar issues on AddFriendRow in SearchFriend
2. Solution: Add the getFriendRequests call to the home screen and get the avatar on SearchFriend
3. No concerns
4. No blockers
> Added call to getFriendRequests on home screen and fixed error with search friend avatar

- packages/ui/views/welcome/welcome-step-four/index.tsx
The "Get Started" button was getting cut-off under some circumstances, this update guarantees that won't happen.
> ENG-157: re-ordered text and buttons on welcome screen 4

- packages/ui/views/account/activity/pending/index.tsx
- packages/ui/views/welcome/welcome-step-four/index.tsx
A simple hack to eliminate the duplicate child warning, PayPal requests can be either "from" me or "to" me, so we add something to the key to represent this directionality. This eliminates the warning.
> Fix duplicate child warning

- __tests__/lndr/format.ts
- packages/lndr/format/index.ts
1. Jira: https://blockmason.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=ENG&selectedIssue=ENG-186
2. Problem: The conversion from Eth to fiat on the Home screen and MyAccount screen was showing more than 2 decimals places
3. Solution: Update the formatting function to show 0 or 2 decimals (depending on the currency)
4. No concerns or tradeoffs, this was very straight-forward
5. No blockers
> Eth fiat format

- android/app/build.gradle
- android/app/src/main/java/com/lndr/MainApplication.java
- packages/actions/util.ts
1. Jira: https://blockmason.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=ENG&selectedIssue=ENG-187
2. Problem: When the user has fingerprint auth enabled and leaves the app running in the background, when they come back to the app, they are asked to use their fingerprint to unlock. If they click 'Cancel' they are still allowed into the app.
3. Solution: If the user clicks 'Cancel' from the fingerprint auth alert, delete the stored user object, which will bring up the PIN auth screen.
4. No concerns
5. No blockers
> Fixed fingerprint auth failure

- ios/LNDR.xcodeproj/project.pbxproj
- ios/LNDR/Info.plist
- ios/Podfile.lock
- packages/lndr/kyc/index.ts
- packages/ui/dialogs/my-account/index.tsx
- packages/ui/forms/verify-identity/index.tsx
1. Problem: the JSON being passed for KYC included the idDocs array. This array is used to create the accounts, but should not be passed to SumSub. The 
2. Solution: move the idDocs property up a level in the KYC object for the server. 
3. Concerns: none
4. Blockers: Note, this is a breaking change and will only work once the server PR (https://github.com/blockmason/lndr/pull/201) has been merged
This PR also contains changes to make the iOS build work correctly in the new XCode
> KYC fixes based on SumSub comments. Moved idDocs array up one level

- packages/ui/dialogs/friend-detail/index.tsx
In lieu of making it easier to transfer ERC-20 amongst friends and overall usefulness of Lndr, this PR adds the ability to view and copy your friend's wallet address. The address is hidden by default and visible by toggling the familiar disclosure arrow (same as My Account).
> View and copy a friend's wallet address

- android/app/build.gradle
- ios/LNDR/Info.plist
- packages/actions/index.ts
- packages/credit-protocol/index.ts
- packages/credit-protocol/lib/credit-record.ts
- packages/lndr/pending-bilateral/index.ts
- packages/ui/dialogs/settlement/index.tsx
1. Jira: https://blockmason.atlassian.net/secure/RapidBoard.jspa?rapidView=9&modal=detail&selectedIssue=LNDR-77
2. Problem: Needed to update the version number and build number on Android and iOS, also had an issue with settlements when the amount was the entire amount but also in a different currency.
3. Solution: Changed the logic for submitting a "multi-settlement" to include situations where the user is attempting to clear the entire balance of a debt/loan that is not in the user's primary currency. Is this situation, we can submit a list with a single transaction to the `multi-settlement` endpoint using the same logic as when there are multiple balances across different currencies.
4. No trade-offs
5. Server fix has already gone through and is confirmed to be working, no blockers
> Lndr updates for BNB settlements

- .gitignore
- README.md
- ios/LNDR/Info.plist
- packages/actions/index.ts
- packages/credit-protocol/index.ts
- packages/credit-protocol/lib/credit-record.ts
- packages/ui/views/account/home/index.tsx
- packages/ui/views/confirmation/index.tsx
- packages/ui/views/new-transaction/index.tsx
- packages/ui/views/request-detail/index.tsx
Problem: Dynamic links for sending transactions were too long
Solution: Generate a short dynamic link followed by the tx hash for linked transactions, and adjust the initialization code to use the new `hash` parameter
> Shorten dynamic link

- android/app/build.gradle
Shortest-path PR to adding 64-bit support to Android builds to satisfy Google Play requirement that takes effect on August 1, 2019.
> 📦 Add 64-bit support to Android builds (v2.0.1)
